# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitClarity < Formula
  desc "Commit-centric pipeline status TUI for trunk-based development via git refs"
  homepage "https://github.com/ezcdlabs/clarity"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ezcdlabs/clarity/releases/download/v0.13.0/git-clarity_0.13.0_darwin_amd64.tar.gz"
      sha256 "a116f802de8562b1fdb231af41da3b54585a92673de9c0c64024505011c92043"

      define_method(:install) do
        bin.install "git-clarity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ezcdlabs/clarity/releases/download/v0.13.0/git-clarity_0.13.0_darwin_arm64.tar.gz"
      sha256 "e78dfcfc030ea00c56512c661d43f72c49a8eeb27f384adb90810aa11d44805c"

      define_method(:install) do
        bin.install "git-clarity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezcdlabs/clarity/releases/download/v0.13.0/git-clarity_0.13.0_linux_amd64.tar.gz"
      sha256 "d445d29f8b3c27257345bf279a5ea6e8cb28215ace18a17071145f383a1829ac"
      define_method(:install) do
        bin.install "git-clarity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezcdlabs/clarity/releases/download/v0.13.0/git-clarity_0.13.0_linux_arm64.tar.gz"
      sha256 "0e506b67bb9a43f246f620b018a8246f52bbfd82613bc527d63dfbc1f948aa6d"
      define_method(:install) do
        bin.install "git-clarity"
      end
    end
  end

  test do
    system "#{bin}/git-clarity", "--version"
  end
end
