# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPushq < Formula
  desc "Serverless push queue for trunk-based development via git refs"
  homepage "https://github.com/ezcdlabs/pushq"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.2/git-pushq_0.0.2_darwin_amd64.tar.gz"
      sha256 "dd942c4e61876c7160e6d2d5a45a455999d06e3b890b0bd3470b9ddf3330a105"

      define_method(:install) do
        bin.install "git-pushq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.2/git-pushq_0.0.2_darwin_arm64.tar.gz"
      sha256 "141d0dc24a6071144f3e4a03dd3ce9991c09f40f7515bdea6b306ade7bd3a969"

      define_method(:install) do
        bin.install "git-pushq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.2/git-pushq_0.0.2_linux_amd64.tar.gz"
      sha256 "76746777545a80c306ef2af0a5191a01642640b783d96446c21bd235c1599466"
      define_method(:install) do
        bin.install "git-pushq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.2/git-pushq_0.0.2_linux_arm64.tar.gz"
      sha256 "2f58665888afffe9f3145f7c8efcabba029feb4dcd3649ed424b0a17b7b044cd"
      define_method(:install) do
        bin.install "git-pushq"
      end
    end
  end

  test do
    system "#{bin}/git-pushq", "--version"
  end
end
