# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPushq < Formula
  desc "Serverless push queue for trunk-based development via git refs"
  homepage "https://github.com/ezcdlabs/pushq"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.3/git-pushq_0.0.3_darwin_amd64.tar.gz"
      sha256 "422a97b5b4bd072473883d35385c1ba4097a35d59ce69f37c74313085fd90e36"

      define_method(:install) do
        bin.install "git-pushq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.3/git-pushq_0.0.3_darwin_arm64.tar.gz"
      sha256 "2d56ae4ed6bf097a23dd7d61b88542d54d6bec1b70f16a09d6ef68cdd7ae2d44"

      define_method(:install) do
        bin.install "git-pushq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.3/git-pushq_0.0.3_linux_amd64.tar.gz"
      sha256 "46de79b87b717171eda891c07d34fa0d4aea58d7b1366d035bca5f0e0b649beb"
      define_method(:install) do
        bin.install "git-pushq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.3/git-pushq_0.0.3_linux_arm64.tar.gz"
      sha256 "e2bb5940e6d1f9dc6f700550ec593b231b69df102e0e02ee1eef24c09d41fd1b"
      define_method(:install) do
        bin.install "git-pushq"
      end
    end
  end

  test do
    system "#{bin}/git-pushq", "--version"
  end
end
