# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPushq < Formula
  desc "Serverless push queue for trunk-based development via git refs"
  homepage "https://github.com/ezcdlabs/pushq"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.1/git-pushq_0.0.1_darwin_amd64.tar.gz"
      sha256 "963ef83ca9508a0721dfba56074067d02ce1e1a61d44caf26745e394ef30f9f4"

      define_method(:install) do
        bin.install "git-pushq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.1/git-pushq_0.0.1_darwin_arm64.tar.gz"
      sha256 "487a8f0f7e504169aec118a77746c24f20d0242db18cf08c1ecfff479657eb1f"

      define_method(:install) do
        bin.install "git-pushq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.1/git-pushq_0.0.1_linux_amd64.tar.gz"
      sha256 "c988d787d398ee655c5c55a7f78f5b2d347223c730fc61c8534fcf472a5238c7"
      define_method(:install) do
        bin.install "git-pushq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezcdlabs/pushq/releases/download/v0.0.1/git-pushq_0.0.1_linux_arm64.tar.gz"
      sha256 "4f7fd75a029051c69c5c299aabb81c61fc6d7acb21a8d0e59a59a1bd7607d87f"
      define_method(:install) do
        bin.install "git-pushq"
      end
    end
  end

  test do
    system "#{bin}/git-pushq", "--version"
  end
end
